[project]
name = "dogs-backend"
version = "0.1.0"
description = "Backend for the dogs project"
authors = [
    {name = "Gemini"}
]
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "fastapi[all] (>=0.127.0,<0.128.0)",
    "sqlmodel (>=0.0.29,<0.0.30)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "alembic (>=1.17.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"

